services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9480:9080"
    volumes:
      - .:/app:rw
    environment:
      MONGO_DB_DSN: mongodb://root:example@mongo:27017/platform
      PORT: 9080
    command:
      - go
      - run
      - .
      - app
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - mongo_data:/data/db
    ports:
      - 27117:27017
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongo localhost:27017/test --quiet
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 30s
volumes:
  mongo_data:
