services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9480:9080"
    volumes:
      - .:/app:rw
    environment:
      PORT: 9080
      MONGO_DB_DSN: mongodb://root:example@mongo:27017/platform
      REDIS_DB_DSN: redis://redis:6379/0?protocol=3
      SESSION_COOKIE_NAME: platform_session
      SESSION_PREFIX: platform_database_platform_cache_
      SESSION_USER_KEY: login_web_59ba36addc2b2f9401580f014c7f58ea4e30989d
      APP_KEY: base64:0oGASEQfjpklH0f37SrmTtxLtNsC8iX1J7eNAqVfqQs=
    command:
      - go
      - run
      - .
      - app
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - mongo_data:/data/db
    ports:
      - 27117:27017
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongo localhost:27017/test --quiet
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 30s
volumes:
  mongo_data:
